title: "Jesse Wiki Docs"

lang: zh_CN.UTF-8
description: "GitHub Pages Jesse documentation."

timezone: "Asia/Shanghai"
encoding: "utf-8"

##
# highlighter-theme: monokai
# date_format: "%Y-%m-%d"

remote_theme: rundocs/jekyll-rtd-theme

markdown: kramdown 

# 对侧边栏进行排序 默认按path排序
# 排序后的文件将根据您的输入具有一定的顺序！
# 如果您要关闭toctree中的订单前缀，
# show_sorted: false

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

meta:
  key1：value1 
  key2：value2 

mathjax: # this will prased to json, default: {}

mermaid:
  custom:     # mermaid link
  initialize: # this will prased to json, default: {}

scss:   # also _includes/extra/styles.scss
script: # also _includes/extra/script.js

translate:
  # 翻译： 简码
  danger:
  # 危险
  note:
  # 注意
  tip:
  # 提示
  warning:
  # 警告
  # 404
  not_found:
  # copyright
  revision:
  # 搜索
  searching:
  search:
  search_docs:
  search_results:
  search_results_found: # the "#" in this translate will replaced with results size!
  search_results_not_found:

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions